[Bug] fixing regression (#422)
In regression tests, accuracy comparison was added for llms. But it
broke the vision model benchmarking script.
```
Running command: python /workspace/hidet/tests/benchmarks/bench_transformer.py bert-base-uncased --params bs=16,seqlen=256 --dtype float16 --backend hidet --mode max-autotune
  File "/workspace/hidet/tests/benchmarks/run_tests.py", line 82, in <module>
    latency = float(outputs.split('\n')[-2])
ValueError: could not convert string to float: "       device='cuda:0', dtype=torch.float16))"
```
Fixed  it!

---------

Co-authored-by: Zhumakhan <nazirzhumakhan@gmail,.com>