[BUG] Simplify symbol variables (#966)
When deserializing the outputs of compiled graph, we catch errors
relates to symbolic variables:
```
return Deserializer(obj, tensors).deserialize(obj)
....
ValueError: Can not simplify expression s0 to an integer

```

This PR fixes it by allowing symbolic variables go through Simplifier
with `instantiate_symbols=True`

---------

Co-authored-by: Zhumakhan <nazirzhumakhan@gmail,.com>
(cherry picked from commit 7083ad06d24bb4d3103368805af9521fec17e6d7)