[Stream] Change the impl of get_current_stream (#694)
When adding the AMD GPU backend for hidet, we meet one issue in building
hidet runtime library during our runtime accessing the cuda/hip stream
from PyTorch C++ side:
```
In file included from hidet/lib/python3.10/site-packages/torch/include/c10/cuda/CUDADeviceAssertionHost.h:3,
                 from hidet/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAException.h:3,
                 from hidet/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAFunctions.h:12,
                 from hidet/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAStream.h:7,
                 from hidet/runtime/hidet_torch/cuda_stream.cpp:1:
hidet/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAMacros.h:8:10: fatal error: c10/cuda/impl/cuda_cmake_macros.h: No such file or directory
    8 | #include <c10/cuda/impl/cuda_cmake_macros.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

After some investigation, we need to configure the build configuration
correctly before including the header of pytorch (so that the current API
works on ROCm platform (there are some build-time macros to specify the
platform)).

Option 1: We can explore more on the PyTorch C++ side to access the ROCm
hip stream and adopt to our current wrapper library. But it would take
more time.

Option 2: We can also fall back to query this stream in python side.
After some benchmark, I found that the overhead of querying in python
side is reasonable and this PR adopts this option.

Using the following scripts to benchmark the `get_current_stream()`
runtime api:
```python
import hidet
import timeit

def main():
    number = 10000

    hidet.option.use_torch_stream(False)
    latency = timeit.timeit(
        stmt='hidet.ffi.runtime_api.get_current_stream()',
        number=number,
        globals=globals()
    )
    print('Use native stream: {:.5} seconds'.format(latency))

    hidet.option.use_torch_stream(True)
    latency = timeit.timeit(
        stmt='hidet.ffi.runtime_api.get_current_stream()',
        number=number,
        globals=globals()
    )
    print('Use torch stream: {:.5} seconds'.format(latency))

if __name__ == '__main__':
    main()
```
The result:
```
Before change:
Use native stream: 0.0030637 seconds
Use torch stream: 0.20911 seconds

After change:
Use native stream: 0.003065 seconds
Use torch stream: 0.2845 seconds
```
Finally, query the torch stream (in C++ side) takes around 75% time and
extra overhead of querying from python side takes about 25% time. This
time is acceptable since we can support both NV/AMD in a more clean way.
And with CUDA graph, this overhead will becomes more negligible.

(cherry picked from commit 324447536c84425b6e6e74778ebb8d6d4a71c5d0)