[Operator] Adding `__ge__` method for the `Tensor` class (#330)
Currently the `Tensor` class does not have a `__ge__` method, which
leads to an error during a model compilation:

> torch._dynamo.exc.BackendCompilerFailed: backend='hidet' raised:
> RuntimeError: '>=' not supported between instances of 'Tensor' and
'float', occurred when interpreting operator.ge with
>   ge(tensor(...), 0.001)
> ge is defined at
> File
"/home/bolin/Desktop/hidet/python/hidet/graph/frontend/torch/register_functions.py",
line 1123

This can be solved by adding `__ge__` special method in the `Tensor`
class.