[Dependency] Remove the version restriction of transformers and diffuers (#475)
The old version of `diffusers` used a depreciated (now completed
removed) api in `huggingface_hub`. Thus, it's better to keep the
versions up to date to prevent such problems in the future.

The error log in our ci:
```text
ImportError while importing test module '/__w/hidet/hidet/tests/apps/test_pretrained.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/__w/_tool/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/apps/test_pretrained.py:14: in <module>
    from hidet.apps import PretrainedModel, hf
/__w/_tool/Python/3.8.18/x64/lib/python3.8/site-packages/hidet/apps/hf.py:16: in <module>
    from diffusers import StableDiffusionPipeline
/__w/_tool/Python/3.8.18/x64/lib/python3.8/site-packages/diffusers/__init__.py:5: in <module>
    from .utils import (
/__w/_tool/Python/3.8.18/x64/lib/python3.8/site-packages/diffusers/utils/__init__.py:[38](https://github.com/hidet-org/hidet/actions/runs/11719752494/job/32643700257#step:9:40): in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
/__w/_tool/Python/3.8.18/x64/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py:28: in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
E   ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/__w/_tool/Python/3.8.18/x64/lib/python3.8/site-packages/huggingface_hub/__init__.py)
```

Also increase the tol in one flaky test.