[Fix] Fix the bug in `tensor_expand` caused by attempting to modify `immutable_list` (#320)
As discussed on our Slack channel, the compilation of the model
`dalle2_pytorch` caused a Hidet exception triggered by `expand`:

> RuntimeError: 'immutable_list' object does not support mutation. If
you are attempting to modify the kwargs or args of a torch.fx.Node
object,
> instead create a new copy of it and assign the copy to the node:
>     new_args = ... # copy and mutate args
>     node.args = new_args
> , occurred when interpreting expand with
>   tensor_expand(tensor(...), [-1, 2, -1])

This PR fixes this bug.