[Fix] Fixing a RuntimeError triggered by `tensor_reshape` function in `register_functions.py` (#328)
Previously, during multiple compilation runs, a mysterious-looking error
like this was encountered:

> torch._dynamo.exc.BackendCompilerFailed: backend='hidet' raised:
> RuntimeError: , occurred when interpreting reshape with
> tensor_reshape(tensor(...), (4741, 4))

The cause is that, if the `shape` argument passed to `tensor_shape` is a
tuple, then in the call `return ops.reshape(self, shape)`, the `shape`
passed to `ops.reshape` will be a single-element tuple, with its only
element being the `shape` tuple passed to `tensor_reshape`.

This PR fixes the issue.