[Fix] Fixing an error triggered by `ClampOp` (#329)
After disallowing functions unsupported by Hidet as in #317 , the
compilation of the model `vision_maskrcnn` (previously failed on
unsupported `topk` method, as in #267 ) failed on a TypeError with the
following traceback message:

> File
"/home/bolin/Desktop/hidet/python/hidet/graph/graph_utils/functors.py",
line 75, in visit
> ret = self.visit_Operator(obj) # pylint: disable=assignment-from-none
>           ^^^^^^^^^^^^^^^^^^^^^^^^
> File
"/home/bolin/Desktop/hidet/python/hidet/graph/graph_utils/functors.py",
line 126, in visit_Operator
>     updated_outputs = op.reforward(inputs)
>                       ^^^^^^^^^^^^^^^^^^^^
> File "/home/bolin/Desktop/hidet/python/hidet/graph/operator.py", line
185, in reforward
>     return cls(*inputs, **attributes).outputs
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> torch._dynamo.exc.BackendCompilerFailed: backend='hidet' raised:
> TypeError: ClampOp.__init__() missing 2 required positional arguments:
'min_value' and 'max_value'


The cause is that, inside the[ `reforward`
function](https://github.com/CentML/hidet/blob/da56e48148c5b075f1fba6d1d878a82889c9f731/python/hidet/graph/operator.py#L180-L185),
during the call to `cls(*inputs, **attributes)`, where `cls` is
`ClampOp`, `inputs` only consists of the input tensor and `attributes`
is an empty dictionary, so the `min_value` and `max_values` cannot be
passed to the initializer. This is because we did not initialize the
`attributes` dictionary to contain the values of these two parameter
[while initializing
`ClampOp`](https://github.com/CentML/hidet/blob/da56e48148c5b075f1fba6d1d878a82889c9f731/python/hidet/graph/ops/arithmetic.py#L586-L595).